service: cross-garden-pollination-server

custom:
  s3Bucket: ${self:service}-${self:provider.stage}
  webpack:
    includeModules: true # enable auto-packing of external modules

plugins:
  - serverless-webpack
  # - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs12.x
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}
  environment:
    ENV: ${self:provider.stage}
    S3_BUCKET: ${self:custom.s3Bucket}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - arn:aws:s3:::${self:custom.s3Bucket}/*

functions:
  githubOauth:
    handler: lib/index.handler
    events:
      - http:
          method: post
          path: /
          cors: true

resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.s3Bucket}
