name: Deploy website example

on:
  pull_request:
  push:

jobs:
  test-and-deploy-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1

      - name: Install all plugins
        run: npm ci
      - name: Build all plugins
        run: npm run build

      # - run: npm run test

      - name: Install example
        run: npm ci
        working-directory: example
      - name: Build example
        run: npm run build -- --prefix-paths
        working-directory: example
        env:
          ROAM_URL: ${{ secrets.ROAM_URL }}
          ROAM_EMAIL: ${{ secrets.ROAM_EMAIL }}
          ROAM_PASSWORD: ${{ secrets.ROAM_PASSWORD }}

      - name: Deploy to the gh-pages branch
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example/public
