name: Test plugin

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test-plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1

      - run: npm ci
      - run: npm run build

      - run: npm ci
        working-directory: example
      - run: npm run build
        working-directory: example
        env:
          ROAM_URL: ${{ secrets.ROAM_URL }}
          ROAM_EMAIL: ${{ secrets.ROAM_EMAIL }}
          ROAM_PASSWORD: ${{ secrets.ROAM_PASSWORD }}
      # - run: npm run test
