name: Test plugin

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  landing-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1

      - run: npm ci
      - run: npm run build
      # - run: npm run test
